_cations = [
    ['H', 'hydrogen', 1],
    ['Li', 'lithium', 1],
    ['Be', 'beryllium', 2],
    ['Na', 'sodium', 1],
    ['Mg', 'magnesium', 2],
    ['Al', 'aluminum', 3],
    ['K', 'potassium', 1],
    ['Ca', 'calcium', 2],
    ['Ba', 'barium', 2],
    ['NH4', 'ammonium', 1, true],
];

_anions = [
    ['O', 'oxide', -2],
    ['F', 'fluoride', -1],
    ['S', ['sulphide', 'sulfide'], -2],
    ['Cl', 'chloride', -1],
    ['Br', 'bromide', -1],
    ['I', 'iodide', -1],
    ['OH', 'hydroxide', -1, true],
    ['CN', 'cyanide', -1, true],
    ['OCN', 'cyanate', -1, true],
    ['SCN', 'thiocyanate', -1, true],
    ['ClO', 'hypochlorite', -1, true],
    ['ClO2', 'chlorite', -1, true],
    ['ClO3', 'chlorate', -1, true],
    ['ClO4', 'perchlorate', -1, true],
    ['IO', 'hypoiodite', -1, true],
    ['IO2', 'iodite', -1, true],
    ['IO3', 'iodate', -1, true],
    ['IO4', 'periodate', -1, true],
    ['BrO', 'hypobromite', -1, true],
    ['BrO2', 'bromite', -1, true],
    ['BrO3', 'bromate', -1, true],
    ['BrO4', 'perbromate', -1, true],
    ['NO2', 'nitrite', -1, true],
    ['NO3', 'nitrate', -1, true],
    ['SO2', ['hyposulphite', 'hyposulfite'], -2, true],
    ['SO3', ['sulphite', 'sulfite'], -2, true],
    ['SO4', ['sulphate', 'sulfate'], -2, true],
    ['SO5', ['persulphate', 'persulfate'], -2, true],
    ['S2O3', ['thiosulphate', 'thiosulfate'], -2, true],
    ['CO3', 'carbonate', -2, true],
    ['HCO3', ['hydrogen carbonate', 'bicarbonate'], -1, true],
    ['CrO4', 'chromate', -2, true],
    ['Cr2O7', 'dichromate', -2, true],
    ['C2O4', 'oxalate', -2, true],
    ['PO2', 'hypophosphite', -3, true],
    ['PO3', 'phosphite', -3, true],
    ['PO4', 'phosphate', -3, true],
    ['PO5', 'perphosphate', -3, true],
    ['HPO4', 'monohydrogen phosphate', -2, true],
    ['H2PO4', 'dihydrogen phosphate', -1, true],
    ['MnO4', 'permanganate', -1, true]
];
